networks:
  app_network:
    driver: bridge

services:
  # Backend Service
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - NATS_URL=${NATS_URL}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - nats
      - mongo
    networks:
      - app_network

  # NATS Service with WebSocket and JetStream
  nats:
    image: nats
    ports:
      - "${NATS_PORT}:4222"      # NATS client port
      - "${NATS_WS_PORT}:8080"   # WebSocket port for NATS WebSocket connections
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    command: -c /etc/nats/nats.conf
    networks:
      - app_network

  # MongoDB Service
  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:
    driver: local
