networks:
  app_network:
    driver: bridge

services:
  # Backend Service
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - NATS_URL=${NATS_URL}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - nats
      - mongo
    networks:
      - app_network

  # NATS Service
  nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      - app_network

  # MongoDB Service
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:
    driver: local
